id: google
display_name: Google Workspace
grant_types:
  - authorization_code
  - refresh_token
auth_url: https://accounts.google.com/o/oauth2/v2/auth
token_url: https://oauth2.googleapis.com/token
scopes:
  - https://www.googleapis.com/auth/userinfo.email
  - https://www.googleapis.com/auth/userinfo.profile
  - https://www.googleapis.com/auth/calendar.readonly
redirect_uri_templates:
  - "{api_base}/oauth/callback/{tenant}/{provider}"
token_endpoint_auth_methods:
  - client_secret_post
docs_url: https://developers.google.com/identity/protocols/oauth2
notes: Domain-wide delegation requires service account impersonation.
webhook_requirements:
  needs_webhook: false
metadata:
  service: google-workspace
  category: productivity
