id: microsoft-graph
display_name: Microsoft Graph
grant_types:
  - authorization_code
  - refresh_token
  - client_credentials
  - device_code
auth_url: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url: https://login.microsoftonline.com/common/oauth2/v2.0/token
device_code_url: https://login.microsoftonline.com/common/oauth2/v2.0/devicecode
scopes:
  - offline_access
  - openid
  - User.Read
  - Mail.Read
  - Calendars.Read
redirect_uri_templates:
  - "{api_base}/oauth/callback/{tenant}/{provider}"
token_endpoint_auth_methods:
  - client_secret_basic
  - client_secret_post
  - private_key_jwt
docs_url: https://learn.microsoft.com/graph/auth-v2-user
notes: Default tenant-wide application permissions for delegated Graph access.
webhook_requirements:
  needs_webhook: false
metadata:
  service: microsoft-graph
  category: productivity
  compliance:
    gdpr: true
