id: slack
display_name: Slack
grant_types:
  - authorization_code
  - refresh_token
auth_url: https://slack.com/oauth/v2/authorize
token_url: https://slack.com/api/oauth.v2.access
scopes:
  - channels:read
  - chat:write
  - files:write
redirect_uri_templates:
  - "{api_base}/oauth/callback/{tenant}/{provider}"
token_endpoint_auth_methods:
  - client_secret_post
docs_url: https://api.slack.com/authentication/oauth-v2
notes: Requires workspace admin approval for production installations.
webhook_requirements:
  needs_webhook: true
  verify_doc: https://api.slack.com/apis/connections/events-api
  event_examples:
    - message.channels
metadata:
  service: slack
  category: collaboration
